# NumPy
- Designed for fast numerical computing.
- It has ndarray which are homogenous, optimized with C Lang.
- Imported as -> import numpy as np.
- Faster than python lists.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


## NumPy Array V/S Python Lists
- NumPy arrays are faster(optimized in C).
- NumPy stroes data in continuous memory blocks.
- Uses less memory (optimized storage).
- Built-in mathematical functions.
- Supports direct vectorized operations.

In [3]:
import time

In [4]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end- start} seconds")

#numpy array
np_arr = np.array(py_list)
start = time.time()
# vectorization
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end- start} seconds")

python list time = 0.3650336265563965 seconds
numpy array time = 0.01628708839416504 seconds


In [5]:
#memory usuage
import sys
print(f"Python List Size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"NumPy Array Size = {np_arr.nbytes} bytes")

Python List Size = 8000056000000 bytes
NumPy Array Size = 8000000 bytes


So why is NumPy faster?
- Homogenous data types and contiguous memory
- Vector Operations and C implementations
- Reduced Overhead

## Creating Numpy Arrays
- From python lists
- From built-in functions

In [6]:
# from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

#2d arrays
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,type(arr2D),arr2.dtype,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> <U21 (3, 3)


In [7]:
# built-in functions
arr0 = np.zeros((2,3),dtype = "int64" )   # prefill by zeros
print(arr0,arr0.shape)

arr1 = np.ones((4,2),dtype = "int64" )     # prefill by ones
print(arr1,arr1.shape)

arr2 = np.full((5,3) ,4)     # prefill by value
print(arr2)

arr3 = np.eye(2,dtype = "int64")     # identity matrix
print(arr3)

arr4 = np.arange(5,30,4)     # range elements(start, stop, step)
print(arr4)

arr5 = np.linspace(1,100 ,4)     #start,end,no of elements wanted in the range
print(arr5)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1]
 [1 1]
 [1 1]
 [1 1]] (4, 2)
[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]
[[1 0]
 [0 1]]
[ 5  9 13 17 21 25 29]
[  1.  34.  67. 100.]


## Properties of NumPy arrays

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# shape
print(arr.shape)

#size
print(arr.size)

#data type
print(arr.dtype)

# dimensions
print(arr.ndim)

# type casting
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


## Operations on Arrays

In [9]:
# Reshaping arrays (equal number of elements while reshaping)
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

# flattening array
flattened = arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [10]:
# indexing 
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2])

ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar[0][0])
print(ar[1][2])
print(ar[2][0])

# fancy indexing
idx = [0,1,3]
print(arr[idx])

# boolean indexing
print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

1
2
3
1
6
7
[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [11]:
# slicing array
arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:5:2])

[2 3 4]
[2 4]


In [12]:
# copy v/s view
py_list = [1,2,3,4,5]
sub_list = py_list[1:4]
print(sub_list)
sub_list[0] = 200                      
print(sub_list)                  # copy
print(py_list)

num_arr = np.array([1,2,3,4,5])
sub_arr = num_arr[1:4]
print(sub_arr)
sub_arr[0] = 200                 # view
print(sub_arr)
print(num_arr)

# for making ccopy in numpy array we can use .copy function

[2, 3, 4]
[200, 3, 4]
[1, 2, 3, 4, 5]
[2 3 4]
[200   3   4]
[  1 200   3   4   5]


## Data Types
- Integer(int32,int64)
- Floating Point nums(float32, float 64)
- Boolean(bool)
- Complex nums(complex64, complex128)
- String($(byte-str), U(unicode-str))
- Object(generic python objects(object))

## Multidimensional Arrays
- 1D -> 1 axis
- 2D -> 2 axes
- 3D -> 3 axes
- 4D -> 4 axes
- 5D -> 5 axes ... 

In [13]:
print(arr2D)

print(np.sum(arr2D))

sum_of_col = np.sum(arr2D, axis = 0)
print(sum_of_col)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [14]:
# 3D Array
arr3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3D,arr3D.shape)

print(np.sum(arr3D))

print(arr3D[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
36
7
