# NumPy
- Designed for fast numerical computing.
- It has ndarray which are homogenous, optimized with C Lang.
- Imported as -> import numpy as np.
- Faster than python lists.

In [1]:
import numpy as np

In [2]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


## NumPy Array V/S Python Lists
- NumPy arrays are faster(optimized in C).
- NumPy stroes data in continuous memory blocks.
- Uses less memory (optimized storage).
- Built-in mathematical functions.
- Supports direct vectorized operations.

In [3]:
import time

In [4]:
#execution performance
size = 1_000_000

#python list
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end- start} seconds")

#numpy array
np_arr = np.array(py_list)
start = time.time()
# vectorization
sq_array = np_arr ** 2
end = time.time()
print(f"numpy array time = {end- start} seconds")

python list time = 0.3434286117553711 seconds
numpy array time = 0.011498451232910156 seconds


In [5]:
#memory usuage
import sys
print(f"Python List Size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"NumPy Array Size = {np_arr.nbytes} bytes")

Python List Size = 8000056000000 bytes
NumPy Array Size = 8000000 bytes


So why is NumPy faster?
- Homogenous data types and contiguous memory
- Vector Operations and C implementations
- Reduced Overhead

## Creating Numpy Arrays
- From python lists
- From built-in functions

In [6]:
# from lists
arr = np.array([1,2,3,4,5])
print(arr,type(arr),arr.dtype,arr.shape)

arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2),arr2.dtype,arr2.shape)

#2d arrays
arr2D = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2D,type(arr2D),arr2.dtype,arr2D.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'> <U21 (6,)
[[1 2 3]
 [4 5 6]
 [7 8 9]] <class 'numpy.ndarray'> <U21 (3, 3)


In [7]:
# built-in functions
arr0 = np.zeros((2,3),dtype = "int64" )   # prefill by zeros
print(arr0,arr0.shape)

arr1 = np.ones((4,2),dtype = "int64" )     # prefill by ones
print(arr1,arr1.shape)

arr2 = np.full((5,3) ,4)     # prefill by value
print(arr2)

arr3 = np.eye(2,dtype = "int64")     # identity matrix
print(arr3)

arr4 = np.arange(5,30,4)     # range elements(start, stop, step)
print(arr4)

arr5 = np.linspace(1,100 ,4)     #start,end,no of elements wanted in the range
print(arr5)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1]
 [1 1]
 [1 1]
 [1 1]] (4, 2)
[[4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]
 [4 4 4]]
[[1 0]
 [0 1]]
[ 5  9 13 17 21 25 29]
[  1.  34.  67. 100.]


## Properties of NumPy arrays

In [8]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

# shape
print(arr.shape)

#size
print(arr.size)

#data type
print(arr.dtype)

# dimensions
print(arr.ndim)

# type casting
float_arr = arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


## Operations on Arrays

In [9]:
# Reshaping arrays (equal number of elements while reshaping)
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)

# flattening array
flattened = arr.flatten()
print(flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [10]:
# indexing 
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[1])
print(arr[2])

ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(ar[0][0])
print(ar[1][2])
print(ar[2][0])

# fancy indexing
idx = [0,1,3]
print(arr[idx])

# boolean indexing
print(arr[arr > 2])
print(arr[arr % 2 == 0])
print(arr[arr % 2 != 0])

1
2
3
1
6
7
[1 2 4]
[3 4 5]
[2 4]
[1 3 5]


In [11]:
# slicing array
arr = np.array([1,2,3,4,5])

print(arr[1:4])
print(arr[1:5:2])

[2 3 4]
[2 4]


In [12]:
# copy v/s view
py_list = [1,2,3,4,5]
sub_list = py_list[1:4]
print(sub_list)
sub_list[0] = 200                      
print(sub_list)                  # copy
print(py_list)

num_arr = np.array([1,2,3,4,5])
sub_arr = num_arr[1:4]
print(sub_arr)
sub_arr[0] = 200                 # view
print(sub_arr)
print(num_arr)

# for making ccopy in numpy array we can use .copy function

[2, 3, 4]
[200, 3, 4]
[1, 2, 3, 4, 5]
[2 3 4]
[200   3   4]
[  1 200   3   4   5]


## Data Types
- Integer(int32,int64)
- Floating Point nums(float32, float 64)
- Boolean(bool)
- Complex nums(complex64, complex128)
- String($(byte-str), U(unicode-str))
- Object(generic python objects(object))

## Multidimensional Arrays
- 1D -> 1 axis
- 2D -> 2 axes
- 3D -> 3 axes
- 4D -> 4 axes
- 5D -> 5 axes ... 

In [13]:
print(arr2D)

print(np.sum(arr2D))

sum_of_col = np.sum(arr2D, axis = 0)
print(sum_of_col)

sum_of_rows = np.sum(arr2D, axis = 1)
print(sum_of_rows)

print(arr2D[0:2, 1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [14]:
# 3D Array
arr3D = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr3D,arr3D.shape)

print(np.sum(arr3D))

print(arr3D[1,1,0])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] (2, 2, 2)
36
7


## Vectorisation and BraodCasting

In [15]:
# vectorisation

arr =  np.array([1,2,3,4,5])
arr1 =  np.array([6,7,8,9,10])

print(arr ** 2)
print(arr + 2)
print(arr + arr1)

[ 1  4  9 16 25]
[3 4 5 6 7]
[ 7  9 11 13 15]


In [16]:
# broadcasting (scaling)

arr1 = np.array([1,2,3,4,5])
arr2 = np.array([[1,2,3,4,5],[1,2,3,4,5]])

print(arr1.shape)
print(arr2.shape)
print(arr1 + arr2)

(5,)
(2, 5)
[[ 2  4  6  8 10]
 [ 2  4  6  8 10]]


## Vector normalisation

Normalizing an array means transforming its values so that they fit into specific scale or range.

In [17]:
# normalise

arr = np.array([[1,2],[3,4]])

mean = np.mean(arr)
std_dev = np.std(arr)

normalised_arr = (arr - mean)/std_dev
print(normalised_arr)

#for normalise arr the mean is 0 and std dev is 1

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


## Important Mathematical Functions

Aggreation ->
- sum()
- prod()
- min()
- max()
- mean()
- std()
- var()
- median()
- argmin()
- argmax()

Power ->
- square()
- sqrt()
- pow(a,b)

Log and exponenetial ->
- log()
- log10()
- log2()
- exp()

Rounding ->
- round()
- floor()
- cell()
- trunc()

Extras -> 
- unique()
- sort()
- abs()

In [18]:
# aggregation

arr = np.array([1,2,3,4,5])

print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))   # index of min value
print(np.argmax(arr))   # index of max value
print(np.mean(arr)) 
print(np.std(arr)) 
print(np.median(arr)) 
print(np.var(arr)) 

15
120
1
5
0
4
3.0
1.4142135623730951
3.0
2.0


In [19]:
# power 
arr = np.array([1,2,3,4,5])

print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,3))

[ 1  4  9 16 25]
[1.         1.41421356 1.73205081 2.         2.23606798]
[  1   8  27  64 125]


In [20]:
# log
arr = np.array([1,2,3,4,5])

print(np.log(arr))          # base e
print(np.log10(arr))
print(np.log2(arr))
print(np.exp(arr))          # e ^ x

[0.         0.69314718 1.09861229 1.38629436 1.60943791]
[0.         0.30103    0.47712125 0.60205999 0.69897   ]
[0.         1.         1.5849625  2.         2.32192809]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591 ]


In [21]:
# rounding off

print(np.round(3.14))
print(np.ceil(3.14))
print(np.floor(3.14))
print(np.trunc(3.14))

3.0
4.0
3.0
3.0


In [22]:
# extra
arr = np.array([1,2,3,1,1,2,-3,-4,4])

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

[-4 -3  1  2  3  4]
[-4 -3  1  1  1  2  2  3  4]
[1 2 3 1 1 2 3 4 4]
